version: 2
jobs:
  #run_tests:
  build:
    docker:
      - image: circleci/node:14.4.0-browsers

    #working_directory: ~/repo

    steps:      
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.6/selenium-server-standalone-3.6.0.jar
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.6.0.jar -log test-reports/selenium.log
          background: true

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test

  deploy:
    docker:
      - image: circleci/node:14.4.0-browsers
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master


#workflows:
#  build_test:
#    jobs:
#      - run_tests

     
 workflows:
   version: 2
   build-deploy:
     jobs:
       - build
       - deploy:
           requires:
             - build # only run deploy-via-git job if the build job has completed
           filters:
             branches:
               only: master # only run deploy-via-git job on master branch